### ISSUE TITLE
Isnt it possible to make a horizontal bar chart?

### ISSUE THREAD

**Issue by danededane** [ricreis394/chartjs-card#6]
First of all I wanna thank you for making this plugin to HA - I'm so happy that I can write my own x values with chartjs. 

I'm having a little trouble when I'm trying to create a horizontal bar chart that should show a positive or negative money value. Here's an example: 

https://www.chartjs.org/docs/latest/samples/bar/horizontal.html

Here's my HA code 

```
`type: 'custom:chartjs-card'
chart: bar
data:
  datasets:
    - backgroundColor: var(--accent-color)
      borderWidth: 2
      data:
        - 1000
      label: Heat
options:
  indexAxis: 'y'
  responsive: true`
```

Even though I'm writing indexaxis: 'y' I'm getting a normal vertical graph .. how can that be ? 

![image](https://user-images.githubusercontent.com/9024493/123658543-1e1b4480-d832-11eb-9733-7feae9d99f1e.png)

**Comment by plckr** [comment]
Hello, thanks!

Please note that this plugin a bit outdated, it uses chartjs 2.9.3
Please see this docs https://www.chartjs.org/docs/2.9.4/

**Comment by danededane** [comment]
Hi again , Thanks for the advice.  I've managed to make a horizontalBar using this code below (Perhaps it can be an inspiration for others)

```
card_mod:
  style: |
    ha-card {
      --bar-color: {% if states('sensor.mariadb_yearly_heat_comparison') > "0" %} 'green' {% else %} 'red' {% endif %};
    }
type: 'custom:chartjs-card'
chart: horizontalBar
data:
  datasets:
    - backgroundColor:
        - var(--bar-color)
      borderWidth: 2
      data:
        - '${states["sensor.mariadb_yearly_heat_comparison"].attributes.data}'
      label: Årlig Varmeforbrug
options:
  scales:
    xAxes:
      - display: true
        ticks:
          min: -1000
          max: 1000

```

It's all great but I cannot make card-mod work . I want to make the chart bar red or green if its a negative or positive value. But it just show me a black chart like this:

![image](https://user-images.githubusercontent.com/9024493/123756605-63d11f00-d8bd-11eb-9653-57128cfb8217.png)

Any ideas why? I mean I can write "backgroundColor: var(--accent-color)" why cant I write my own card-mod variable? like backgroundColor: var(--bar-color)?
